#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 17 13:15:23 2021

@author: ayman
"""

from types import SimpleNamespace


params = {'pong': SimpleNamespace(**{'env': 'PongNoFrameskip-v4',
                                     'lr': 1e-4,
                                     'init_replay': 10_000,
                                     'eps_start': 1.0,
                                     'eps_final': 0.02,
                                     'eps_frames': 50_000,
                                     'buffer_size': 100_000,
                                     'gamma': 0.99,
                                     'batch_size': 64,
                                     'solve_rewards': 17,
                                     'sync_nets': 1000,
                                     'seed': 144,
                                     'n_envs': 3,
                                     'frame_stack': 4,
                                     'steps': 4,
                                     'max_steps': None,
                                     'min_lr':1e-4,
                                     'entropy_beta':0.01,
                                     }),
          'breakout': SimpleNamespace(**{'env': 'BreakoutNoFrameskip-v4',
                                         'lr': 1e-4,
                                         'init_replay': 25_000,
                                         'eps_start': 1.0,
                                         'eps_final': 0.1,
                                         'eps_frames': 150_000,
                                         'buffer_size': 250_000,
                                         'gamma': 0.99,
                                         'batch_size': 32,
                                         'solve_rewards': 100,
                                         'sync_nets': 1000,
                                         'seed': 144,
                                         'n_envs': 3,
                                         'frame_stack': 2,
                                         'steps': 4,
                                         'max_steps': None,
                                         'min_lr':1e-5,
                                         'entropy_beta':0.01,
                                         }),
          'invaders': SimpleNamespace(**{'env': 'SpaceInvadersNoFrameskip-v4',
                                         'lr': 1e-4,
                                         'init_replay': 10_000,
                                         'eps_start': 1.0,
                                         'eps_final': 0.02,
                                         'eps_frames': 50_000,
                                         'buffer_size': 250_000,
                                         'gamma': 0.99,
                                         'batch_size': 128,
                                         'solve_rewards': 25,
                                         'sync_nets': 2500,
                                         'seed': 144,
                                         'n_envs': 2,
                                         'frame_stack': 2,
                                         'steps': 4,
                                         'max_steps': None,
                                         'min_lr':1e-6,
                                         'entropy_beta':0.01,
                                         }),
          'boxing': SimpleNamespace(**{'env': 'BoxingNoFrameskip-v4',
                                         'lr': 1e-4,
                                         'init_replay': 10_000,
                                         'eps_start': 1.0,
                                         'eps_final': 0.02,
                                         'eps_frames': 50_000,
                                         'buffer_size': 100_000,
                                         'gamma': 0.97,
                                         'batch_size': 16,
                                         'solve_rewards': 15,
                                         'sync_nets': 1000,
                                         'seed': 155,
                                         'n_envs': 4,
                                         'frame_stack': 4,
                                         'steps': 4,
                                         'max_steps': 300,
                                         'min_lr':1e-6,
                                         'entropy_beta':0.01,
                                         }),
          'bowling': SimpleNamespace(**{'env': 'BowlingNoFrameskip-v4',
                                         'lr': 1e-3,
                                         'init_replay': 10_000,
                                         'eps_start': 1.0,
                                         'eps_final': 0.02,
                                         'eps_frames': 50_000,
                                         'buffer_size': 100_000,
                                         'gamma': 0.97,
                                         'batch_size': 16,
                                         'solve_rewards': 15,
                                         'sync_nets': 1000,
                                         'seed': 155,
                                         'n_envs': 4,
                                         'frame_stack': 4,
                                         'steps': 4,
                                         'max_steps': 300,
                                         'min_lr':1e-5,
                                         'entropy_beta':0.01,
                                         }),
          'demon': SimpleNamespace(**{'env': 'DemonAttackNoFrameskip-v4',
                                         'lr': 1e-3,
                                         'init_replay': 10_000,
                                         'eps_start': 1.0,
                                         'eps_final': 0.02,
                                         'eps_frames': 50_000,
                                         'buffer_size': 100_000,
                                         'gamma': 0.97,
                                         'batch_size': 16,
                                         'solve_rewards': 100,
                                         'sync_nets': 1000,
                                         'seed': 155,
                                         'n_envs': 4,
                                         'frame_stack': 4,
                                         'steps': 4,
                                         'max_steps': 1000,
                                         'min_lr':5e-5,
                                         'entropy_beta':0.01,
                                         }),
          'riverraid': SimpleNamespace(**{'env': 'RiverraidNoFrameskip-v4',
                                         'lr': 1e-3,
                                         'init_replay': 10_000,
                                         'eps_start': 1.0,
                                         'eps_final': 0.02,
                                         'eps_frames': 50_000,
                                         'buffer_size': 100_000,
                                         'gamma': 0.99,
                                         'batch_size': 32,
                                         'solve_rewards': 100,
                                         'sync_nets': 1000,
                                         'seed': 155,
                                         'n_envs': 4,
                                         'frame_stack': 4,
                                         'steps': 4,
                                         'max_steps': None,
                                         'min_lr':5e-5,
                                         'entropy_beta':0.01,
                                         }),


          }


trianable_envs = {'adventure': ' AdventureNoFrameskip-v4',
 'air_raid': ' AirRaidNoFrameskip-v4',
 'alien': ' AlienNoFrameskip-v4',
 'amidar': ' AmidarNoFrameskip-v4',
 'assault': ' AssaultNoFrameskip-v4',
 'asterix': ' AsterixNoFrameskip-v4',
 'asteroids': ' AsteroidsNoFrameskip-v4',
 'atlantis': ' AtlantisNoFrameskip-v4',
 'bank_heist': ' BankHeistNoFrameskip-v4',
 'battle_zone': ' BattleZoneNoFrameskip-v4',
 'beam_rider': ' BeamRiderNoFrameskip-v4',
 'berzerk': ' BerzerkNoFrameskip-v4',
 'bowling': ' BowlingNoFrameskip-v4',
 'boxing': ' BoxingNoFrameskip-v4',
 'breakout': ' BreakoutNoFrameskip-v4',
 'carnival': ' CarnivalNoFrameskip-v4',
 'centipede': ' CentipedeNoFrameskip-v4',
 'chopper_command': ' ChopperCommandNoFrameskip-v4',
 'crazy_climber': ' CrazyClimberNoFrameskip-v4',
 'demon_attack': ' DemonAttackNoFrameskip-v4',
 'double_dunk': ' DoubleDunkNoFrameskip-v4',
 'elevator_action': ' ElevatorActionNoFrameskip-v4',
 'enduro': ' EnduroNoFrameskip-v4',
 'fishing_derby': ' FishingDerbyNoFrameskip-v4',
 'freeway': ' FreewayNoFrameskip-v4',
 'frostbite': ' FrostbiteNoFrameskip-v4',
 'gopher': ' GopherNoFrameskip-v4',
 'gravitar': ' GravitarNoFrameskip-v4',
 'hero': ' HeroNoFrameskip-v4',
 'ice_hockey': ' IceHockeyNoFrameskip-v4',
 'jamesbond': ' JamesbondNoFrameskip-v4',
 'journey_escape': ' JourneyEscapeNoFrameskip-v4',
 'kangaroo': ' KangarooNoFrameskip-v4',
 'krull': ' KrullNoFrameskip-v4',
 'kung_fu_master': ' KungFuMasterNoFrameskip-v4',
 'montezuma_revenge': ' MontezumaRevengeNoFrameskip-v4',
 'ms_pacman': ' MsPacmanNoFrameskip-v4',
 'name_this_game': ' NameThisGameNoFrameskip-v4',
 'phoenix': ' PhoenixNoFrameskip-v4',
 'pitfall': ' PitfallNoFrameskip-v4',
 'pong': ' PongNoFrameskip-v4',
 'pooyan': ' PooyanNoFrameskip-v4',
 'private_eye': ' PrivateEyeNoFrameskip-v4',
 'qbert': ' QbertNoFrameskip-v4',
 'riverraid': ' RiverraidNoFrameskip-v4',
 'road_runner': ' RoadRunnerNoFrameskip-v4',
 'robotank': ' RobotankNoFrameskip-v4',
 'seaquest': ' SeaquestNoFrameskip-v4',
 'skiing': ' SkiingNoFrameskip-v4',
 'solaris': ' SolarisNoFrameskip-v4',
 'space_invaders': ' SpaceInvadersNoFrameskip-v4',
 'star_gunner': ' StarGunnerNoFrameskip-v4',
 'tennis': ' TennisNoFrameskip-v4',
 'time_pilot': ' TimePilotNoFrameskip-v4',
 'tutankham': ' TutankhamNoFrameskip-v4',
 'up_n_down': ' UpNDownNoFrameskip-v4',
 'venture': ' VentureNoFrameskip-v4',
 'video_pinball': ' VideoPinballNoFrameskip-v4',
 'wizard_of_wor': ' WizardOfWorNoFrameskip-v4',
 'yars_revenge': ' YarsRevengeNoFrameskip-v4',
 'zaxxon': ' ZaxxonNoFrameskip-v4'}